app:
  window:
    duration: 1m

spring:
  application:
    name: kstream-sales-aggregation-example
  kafka:
    streams:
      state-dir: ./target/kstream-statestore
      properties:
        bootstrap.servers: localhost:29092
        commit.interval.ms: 100
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler

logging:
  level:
    org.springframework.kafka: DEBUG
